/*
    Copyright (c) 2023 Alethea Katherine Flowers.
    Published under the standard MIT License.
    Full text available at: https://opensource.org/licenses/MIT
*/

/** Board view layer names */
export enum LayerNames {
    dwgs_user = "Dwgs.User",
    cmts_user = "Cmts.User",
    eco1_user = "Eco1.User",
    eco2_user = "Eco2.User",
    edge_cuts = "Edge.Cuts",
    margin = "Margin",
    user_1 = "User.1",
    user_2 = "User.2",
    user_3 = "User.3",
    user_4 = "User.4",
    user_5 = "User.5",
    user_6 = "User.6",
    user_7 = "User.7",
    user_8 = "User.8",
    user_9 = "User.9",
    anchors = ":Anchors",
    non_plated_holes = ":NonPlatedHoles",
    via_holes = ":Via:Holes",
    pad_holes = ":Pad:Holes",
    pad_holewalls = ":Pad:HoleWalls",
    via_holewalls = ":Via:HoleWalls",
    f_cu = "F.Cu",
    f_mask = "F.Mask",
    f_silks = "F.SilkS",
    f_adhes = "F.Adhes",
    f_paste = "F.Paste",
    f_crtyd = "F.CrtYd",
    f_fab = "F.Fab",
    in1_cu = "In1.Cu",
    in2_cu = "In2.Cu",
    in3_cu = "In3.Cu",
    in4_cu = "In4.Cu",
    in5_cu = "In5.Cu",
    in6_cu = "In6.Cu",
    in7_cu = "In7.Cu",
    in8_cu = "In8.Cu",
    in9_cu = "In9.Cu",
    in10_cu = "In10.Cu",
    in11_cu = "In11.Cu",
    in12_cu = "In12.Cu",
    in13_cu = "In13.Cu",
    in14_cu = "In14.Cu",
    in15_cu = "In15.Cu",
    in16_cu = "In16.Cu",
    in17_cu = "In17.Cu",
    in18_cu = "In18.Cu",
    in19_cu = "In19.Cu",
    in20_cu = "In20.Cu",
    in21_cu = "In21.Cu",
    in22_cu = "In22.Cu",
    in23_cu = "In23.Cu",
    in24_cu = "In24.Cu",
    in25_cu = "In25.Cu",
    in26_cu = "In26.Cu",
    in27_cu = "In27.Cu",
    in28_cu = "In28.Cu",
    in29_cu = "In29.Cu",
    in30_cu = "In30.Cu",
    b_cu = "B.Cu",
    b_mask = "B.Mask",
    b_silks = "B.SilkS",
    b_adhes = "B.Adhes",
    b_paste = "B.Paste",
    b_crtyd = "B.CrtYd",
    b_fab = "B.Fab",
}

export const HoleLayerNames = [
    LayerNames.non_plated_holes,
    LayerNames.via_holes,
    LayerNames.pad_holes,
    LayerNames.pad_holewalls,
    LayerNames.via_holewalls,
];

export const CopperLayerNames = [
    LayerNames.f_cu,
    LayerNames.in1_cu,
    LayerNames.in2_cu,
    LayerNames.in3_cu,
    LayerNames.in4_cu,
    LayerNames.in5_cu,
    LayerNames.in6_cu,
    LayerNames.in7_cu,
    LayerNames.in8_cu,
    LayerNames.in9_cu,
    LayerNames.in10_cu,
    LayerNames.in11_cu,
    LayerNames.in12_cu,
    LayerNames.in13_cu,
    LayerNames.in14_cu,
    LayerNames.in15_cu,
    LayerNames.in16_cu,
    LayerNames.in17_cu,
    LayerNames.in18_cu,
    LayerNames.in19_cu,
    LayerNames.in20_cu,
    LayerNames.in21_cu,
    LayerNames.in22_cu,
    LayerNames.in23_cu,
    LayerNames.in24_cu,
    LayerNames.in25_cu,
    LayerNames.in26_cu,
    LayerNames.in27_cu,
    LayerNames.in28_cu,
    LayerNames.in29_cu,
    LayerNames.in30_cu,
    LayerNames.b_cu,
];
